### ISSUE TITLE
Running Failure when running async DDP experiments.

### ISSUE THREAD

**Issue by dixiyao** [suquark/hoplite#169]
When I tried to run the codes under app/parameter-server on slurm cluster, I always get failure with segementation fault. The failure always happens after 
```
hoplite.start_location_server()
ray.init(address='auto', ignore_reinit_error=True)
```
and it will report segementatoin fault. The logging is like this
```
1636525003466554268 object_directory[139.19.15.46]:63378:139778674558912 /home/dixiyao/hoplite/src/object_directory/notification.cc:535 main ]: Starting object directory at 139.19.15.46:7777
1636525003475934778 object_directory[139.19.15.46]:63378:139778485901056 /home/dixiyao/hoplite/src/object_directory/notification.cc:524 worker_loop ]: [NotificationServer] notification server started
2021-11-10 07:16:45,468	INFO worker.py:827 -- Connecting to existing Ray cluster at address: 139.19.15.46:6379
/var/lib/slurm/slurmd/job7000819/slurm_script: line 67: 63357 Segmentation fault      python3 hoplite_all_reduce.py --num-workers=4
```

I have tried this on AWS cluster with one machine and on Slurm with 4 machine (one GPU on each machine for both). Neither of them will succeed and both them reported segementation fault.

Is there any idea about possible causes of this fault. Or could this be result from incorrect installation of Hoplite?

**Comment by suquark** [comment]
Hi, could you run coverage tests successfully?  For example, `microbenchmarks/hoplite-python/coverage_test.sh` (You may change the number of nodes in the script before running it).

**Comment by dixiyao** [comment]
Thanks
It reports this to me when I run conevrage test on AWS
```
/local/home/dyao/hoplite/test_utils/mpirun_pernode.sh: line 5: /opt/amazon/openmpi/bin/mpirun: No such file or directory
./run_test.sh: line 1: kill: (-2062) - No such process
```

**Comment by suquark** [comment]
This is because most benchmarks in Hoplite depends on MPI (specifically OpenMPI). The specific MPI path for some AWS AMIs is `/opt/amazon/openmpi/bin/mpirun`. You can modify `mpirun_pernode.sh` to include your `mpirun`. I believe you can find MPI in most cluster environments.

**Comment by dixiyao** [comment]
My path is directly /bin/mpi, and now I can run Hoplite on AWS. Thanks very much for your help!

**Comment by suquark** [comment]
Hi, does this already address your issues? Thanks!

**Comment by dixiyao** [comment]
Yes, thanks for you help!
